package com.sachintha.dis.webapp.pojo;

import org.jsoup.select.Elements;

import com.sachintha.dis.webapp.service.Message;

// Generated Mar 16, 2018 10:20:48 AM by Hibernate Tools 4.3.1

/**
 * DefectInfo generated by hbm2java
 */
public class DefectInfo implements java.io.Serializable {

	private String rollNo;
	private String goG;
	private String customerC;
	private String ppoNo;
	private String usageU;
	private String comboC;
	private String batchNo;
	private String qtyKgs;
	private String qtyYardage;
	private String originalWd;
	private String actualWd;
	private String defectD;
	private String defectPosition;
	private String batchFocQtyYds;
	private String jobJ;
	private String issueI;
	private String processMethod;
	private String remarkR;
	private String datetimeD;

	public DefectInfo() {
	}

	public DefectInfo(String rollNo) {
		this.rollNo = rollNo;
	}

	public DefectInfo(Elements tds) {
		for (int j = 0; j < tds.size(); j++) {
			if (j == 0) {
				setGoG(tds.get(j).text());
			} else if (j == 1) {
				setCustomerC(tds.get(j).text());
			} else if (j == 6) {
				if (tds.get(j).text().matches("^\\s*$")) {
					setRollNo(null);
				}else{
					setRollNo(tds.get(j).text());
				}
			} else if (j == 2) {
				setPpoNo(tds.get(j).text());
			} else if (j == 3) {
				setUsageU(tds.get(j).text());
			} else if (j == 4) {
				setComboC(tds.get(j).text());
			} else if (j == 5) {
				setBatchNo(tds.get(j).text());
			} else if (j == 7) {
				setQtyKgs(tds.get(j).text());
			} else if (j == 8) {
				setQtyYardage(tds.get(j).text());
			} else if (j == 9) {
				setOriginalWd(tds.get(j).text());
			} else if (j == 10) {
				setActualWd(tds.get(j).text());
			} else if (j == 11) {
				setDefectD(tds.get(j).text());
			} else if (j == 12) {
				setDefectPosition(tds.get(j).text());
			} else if (j == 13) {
				setBatchFocQtyYds(tds.get(j).text());
			} else if (j == 14) {
				setJobJ(tds.get(j).text());
			} else if (j == 15) {
				setIssueI(tds.get(j).text());
			} else if (j == 16) {
				setProcessMethod(tds.get(j).text());
			} else {
				setRemarkR(tds.get(j).text());
			}

		}
	}

	public DefectInfo(String rollNo, String goG, String customerC, String ppoNo, String usageU, String comboC,
			String batchNo, String qtyKgs, String qtyYardage, String originalWd, String actualWd, String defectD,
			String defectPosition, String batchFocQtyYds, String jobJ, String issueI, String processMethod,
			String remarkR) {
		this.rollNo = rollNo;
		this.goG = goG;
		this.customerC = customerC;
		this.ppoNo = ppoNo;
		this.usageU = usageU;
		this.comboC = comboC;
		this.batchNo = batchNo;
		this.qtyKgs = qtyKgs;
		this.qtyYardage = qtyYardage;
		this.originalWd = originalWd;
		this.actualWd = actualWd;
		this.defectD = defectD;
		this.defectPosition = defectPosition;
		this.batchFocQtyYds = batchFocQtyYds;
		this.jobJ = jobJ;
		this.issueI = issueI;
		this.processMethod = processMethod;
		this.remarkR = remarkR;
	}

	public String getRollNo() {
		return this.rollNo;
	}

	public void setRollNo(String rollNo) {
		this.rollNo = rollNo;
	}

	public String getGoG() {
		return this.goG;
	}

	public void setGoG(String goG) {
		this.goG = goG;
	}

	public String getCustomerC() {
		return this.customerC;
	}

	public void setCustomerC(String customerC) {
		this.customerC = customerC;
	}

	public String getPpoNo() {
		return this.ppoNo;
	}

	public void setPpoNo(String ppoNo) {
		this.ppoNo = ppoNo;
	}

	public String getUsageU() {
		return this.usageU;
	}

	public void setUsageU(String usageU) {
		this.usageU = usageU;
	}

	public String getComboC() {
		return this.comboC;
	}

	public void setComboC(String comboC) {
		this.comboC = comboC;
	}

	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public String getQtyKgs() {
		return this.qtyKgs;
	}

	public void setQtyKgs(String qtyKgs) {
		this.qtyKgs = qtyKgs;
	}

	public String getQtyYardage() {
		return this.qtyYardage;
	}

	public void setQtyYardage(String qtyYardage) {
		this.qtyYardage = qtyYardage;
	}

	public String getOriginalWd() {
		return this.originalWd;
	}

	public void setOriginalWd(String originalWd) {
		this.originalWd = originalWd;
	}

	public String getActualWd() {
		return this.actualWd;
	}

	public void setActualWd(String actualWd) {
		this.actualWd = actualWd;
	}

	public String getDefectD() {
		return this.defectD;
	}

	public void setDefectD(String defectD) {
		this.defectD = defectD;
	}

	public String getDefectPosition() {
		return this.defectPosition;
	}

	public void setDefectPosition(String defectPosition) {
		this.defectPosition = defectPosition;
	}

	public String getBatchFocQtyYds() {
		return this.batchFocQtyYds;
	}

	public void setBatchFocQtyYds(String batchFocQtyYds) {
		this.batchFocQtyYds = batchFocQtyYds;
	}

	public String getJobJ() {
		return this.jobJ;
	}

	public void setJobJ(String jobJ) {
		this.jobJ = jobJ;
	}

	public String getIssueI() {
		return this.issueI;
	}

	public void setIssueI(String issueI) {
		this.issueI = issueI;
	}

	public String getProcessMethod() {
		return this.processMethod;
	}

	public void setProcessMethod(String processMethod) {
		this.processMethod = processMethod;
	}

	public String getRemarkR() {
		return this.remarkR;
	}

	public void setRemarkR(String remarkR) {
		this.remarkR = remarkR;
	}

	public String getDatetimeD() {
		return datetimeD;
	}

	public void setDatetimeD(String datetimeD) {
		this.datetimeD = datetimeD;
	}

}
